[package]
name = "libbox"
version = "0.1.0"
authors = ["Harry Stern <hcs@meow.sh>"]
workspace = ".."

[features]
client = ["glium"]
server = []

[dependencies]
specs = "0.7.0"
time = "0.1"
glium = { version = "0.15.0", optional = true }
